### ISSUE TITLE
Change Plugin-opening URI when 0.13 releases

### ISSUE THREAD

**Issue by chrisgrieser** [obsidian-community/obsidian-hub#108]
As a reminder for us when 0.13.x releases to the public:

- [ ] change `obsidian://goto-plugin?` to `obsidian://show-plugin?`
- [ ] remove hover-info from publish.css

**Comment by claremacrae** [comment]
Awesome - thanks for logging this!

**Comment by chrisgrieser** [comment]
This could be changed in a week or so?

**Comment by argenos** [comment]
Yeah, this is an easy one. I'll leave it open in case someone wants to tackle it!

**Comment by chrisgrieser** [comment]
I'd hold on for this one, since there actually is a bug when using the new Obsidian URI while having Hotkey Helper installed: https://github.com/pjeby/hotkey-helper/issues/7

**Comment by chrisgrieser** [comment]
okay, has been fixed super quickly already

**Comment by claremacrae** [comment]
Because this is labelled with "good first issue", I've added the "info needed" label...

This is less about editing the current files, it's updating the template used by the Python scripts, and then regenerating the output.

**Comment by lguenth** [comment]
Closing this since #298 and #299 were merged.
