### ISSUE TITLE
Work out why update-releases.py removed pdf-to-markdown-plugin from akaalias.md

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#119]
In a run of this command:

```bash
python3 ./update-releases.py --all
```

There was this unexpected diff:

```diff
diff --git a/01 - Community/People/akaalias.md b/01 - Community/People/akaalias.md
index 79054a0..d409df0 100644
--- a/01 - Community/People/akaalias.md 
+++ b/01 - Community/People/akaalias.md 
@@ -22,7 +22,6 @@ publish: true
 ### Plugins
 - [[extract-highlights-plugin|Extract Highlights]]
 - [[dangerzone-writing-plugin|Dangerzone Writing]]
-- [[pdf-to-markdown-plugin|PDF to Markdown]]
 - [[obsidian-extract-pdf-highlights|PDF Highlights]]
 - [[obsidian-journey-plugin|Journey]]
 - [[obsidian-footnotes|Footnote Shortcut]]
```

In other words, the line `[[pdf-to-markdown-plugin|PDF to Markdown]]` was removed from `01 - Community/People/akaalias.md`

Code versions:

- On obsidian-releases commit https://github.com/obsidianmd/obsidian-releases/commit/2ff79f2eab141be2f38a646bb93fec2914df65e0
- And obsidian-hub release https://github.com/obsidian-community/obsidian-hub/commit/0ce75636815f752d7391481d3f1299c588bc4b26

I was able to reproduce it by running a second time.

I've checked the contents of both the repos involved, and the plugin's repo - and cannot see any reason for the disappearance.

The plugin is also missing when browsing plugins in Obsidian - even though as far as I can see, it is still in the community plugins list...

**Comment by claremacrae** [comment]
Oh - it was removed from community-plugins.json in the last 24 hours, with no reason why.

https://github.com/obsidianmd/obsidian-releases/commit/af2af335fe58ab755d9f85a89d43df6cb98ba391

So we need to decide whether to remove it from the hub.

I'll leave the author file unchanged for now - so this will show up again, as a reminder, next time the update process is run.

**Comment by claremacrae** [comment]
(I was looking at an out-of-date local copy of `community-plugins.json`, hence my confusion up above.

**Comment by kometenstaub** [comment]
The reason why it got removed is that opening PDFs on mobile doesn't work when the plugin is installed, we had multiple reports of it. The author didn't respond to the issue we opened, so it got pulled.

**Comment by claremacrae** [comment]
Super - thank you!

I'm hoping we'll come up with a way to represent archived plugins and themes in the Hub, in which case this will get picked up.

So I'll close this issue now.
