### ISSUE TITLE
Introduction to Obsidian

### ISSUE THREAD

**Issue by konhi** [obsidian-community/obsidian-hub#18]
I wanted to copy [:octocat: awesome-obsidian/what-is-obsidian](https://github.com/kmaasrud/awesome-obsidian#what-is-obsidian) section, but I couldn't fight right place for it.

If there's no place for it, I suggest creating a note **📁 10 - Resources / 📄 About Obsidian** (or **What is Obsidian**, or maybe something different if anyone has better ideas). It should be a note containing reviews, blog posts, introductions, and roundups of what is Obsidian.

Please, let me know:
1. if there isn't already a place like that in the vault
2. if not, what location and name should be

**Comment by argenos** [comment]
I'd put this under 09.01 in the Obsidian note

**Comment by konhi** [comment]
> 
> 
> I'd put this under 09.01 in the Obsidian note

Thanks for letting me know! I think it fits as well. Do you think **About Obsidian** name is fine, or would you like to suggest any other?

**Comment by argenos** [comment]
Maybe About Obsidian should be a header inside the Obsidian note?
