### ISSUE TITLE
Redlink

### ISSUE THREAD

**Issue by Craftidore** [obsidian-community/obsidian-hub#220]
On [04 → How to Style Obsidian](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/How+to+Style+Obsidian), this link sends me to a 404 error.

![image](https://user-images.githubusercontent.com/73705352/149420106-756d7bd1-e603-4f69-aef3-4bfc202c1dd7.png)

![image](https://user-images.githubusercontent.com/73705352/149420155-ee67e35a-3a6c-48e8-82ff-3a9b9b1b6927.png)

**Comment by dbarenholz** [comment]
<https://www.diamondvogel.com/architectural/blog/2015-pantone-color-of-the-year> can be used to replace!~

**Comment by kometenstaub** [comment]
Fixed in #221
