### ISSUE TITLE
Invalid aliases in 4 wiki links

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#222]
I noticed one odd link...

![image](https://user-images.githubusercontent.com/4840096/149527913-49893c80-5612-4bf4-a20b-f5fb68ebc0f3.png)

So wrote some code to check for other instances of 2 `|` in one wiki link:

```
Error:
  Too many aliases in wiki link: [[Obsidian Community Talks|Obsidian Community Talk|showcase]]:
  ./04 - Guides, Workflows, & Courses/Community Talks/Breadcrumbs Showcase.md 

Error:
  Too many aliases in wiki link: [[obsidian-plugin-todo|Obsidian TODO | Text-based GTD]]:
  ./02 - Community Expansions/02.01 Plugins by Category/Task management plugins.md 

Error:
  Too many aliases in wiki link: [[obsidian-auto-link-title||automatically fetches a page title when you link to it]]:
  ./01 - Community/Obsidian Roundup/2021.08.21.md 

Error:
  Too many aliases in wiki link: [[obsidian-plugin-todo|Obsidian TODO | Text-based GTD]]:
  ./01 - Community/People/larslockefeer.md 
```

**Comment by dbarenholz** [comment]
`[[obsidian-plugin-todo|Obsidian TODO | Text-based GTD]]` should probably be `[[obsidian-plugin-todo|Text-based GTD]]` if I read the plugin page <https://github.com/larslockefeer/obsidian-plugin-todo>.

`[[Obsidian Community Talks|Obsidian Community **Talk|showcase]]` should probably be `[[Obsidian Community Talks|showcase]]` based on the sentence that it's in?

Finally, `[[obsidian-auto-link-title||automatically fetches a page title when you link to it]]` just looks as if there's a `|` too many.

**Comment by claremacrae** [comment]
Hahah - one of the problems is due to the plugin having a | in its name:
https://github.com/larslockefeer/obsidian-plugin-todo/blob/main/manifest.json#L3

![image](https://user-images.githubusercontent.com/4840096/149529767-85d9730a-4763-437e-94e2-6ad06d7baf5c.png)
