### ISSUE TITLE
Ancilliary tools categories

### ISSUE THREAD

**Issue by konhi** [obsidian-community/obsidian-hub#24]
I wanted to copy [:octocat: awesome-obsidian/external-tools](https://github.com/kmaasrud/awesome-obsidian#external-tools) section. These tools are split into categories, such as:
- converters
- browser extensions
- publishing
- other

1. Should there be such categorization in :octocat: **obsidian-hub** as well?
2. If so, how would the structure of folders look like?

**Comment by argenos** [comment]
I would add Topics for each of these and use the links to navigate (I'm doing something similar for backlinking notes in the Obsidian roundup notes), e.g. 
![image](https://user-images.githubusercontent.com/5426039/135716968-1e877cd3-fc96-48da-a9f2-c87f986bb575.png)

I'd say we go for folders if it's always easy to classify the notes, otherwise maybe links are best?

**Comment by argenos** [comment]
I haven't pushed the new notes yet (Still need to apply templates, but you can see some of the changes in #26 already.

**Comment by konhi** [comment]
I agree! Currently structure looks like this:
```
📁 09 - Digital Garden/
├── 📁 09.01 - Topics
│   ├── 📄 Ancilliary tools.md
```

And **📄 Ancilliary tools.md** says:
> 1. Create a new note under **[[10 - Resources]]**

Don't you think it could be better if we'd make structure like this, so we won't use **📁 10 - Resources**?
It would be consistent with **📁 Obsidian** which is also located in **📁 09.01 - Topics.**
```
📁 09 - Digital Garden/
├── 📁 09.01 - Topics
│   ├── 📄 09.01 - Topics.md
│   ├── 📁 Ancilliary tools
│   │   ├── 📄 Ancilliary tools.md
│   │   ├── 📁 Categories
│   │   └── 📁 Tools
```

I think that we also have to add this to tool template:
**Category: #placeholder/category** (which would be a new placeholder). We could also add comment:
> %% Uncomment this and remove those that don't apply: [[Converters]] [[Browser extensions]] [[Publishing]] %%

Is it correct?

**Comment by argenos** [comment]
I have no strong preferences of where to place the `Ancillary tools` folder should be. I originally figured that since these were "external" tools, it made sense to put them in resources, but I'd be ok with putting them under `09 - Topics`, perhaps in a new folder `09.04`

**Comment by argenos** [comment]
Alright, closing this one since auxiliary tools categories were added in the last refactoring.
