### ISSUE TITLE
Suggest making documents friendlier to read on github.com

### ISSUE THREAD

**Issue by tallguyjenks** [obsidian-community/obsidian-hub#3]
**Suggestion:** before starting a PR, Suggest adding a `README.md` file to the root of each of these directories as well as the root of the repo and linking them to each other and to the files they reside next to in the directories like MOC's.

**Reasoning:** the `README.md` files will auto-display on github making it a friendly reading experience that opening individual files and seeing source code. Linking things will also make the reading experience friendlier.

**Negation:** if this repo isnt meant to be a github friendly reading experience and rather just a staging ground for something hosted elsewhere then feel free to close this issue

**Next Step:** Let me know if this sounds good and is a desired change or not and ill open a PR :)

**Comment by argenos** [comment]
I've added a small readme on #2 (as well as some major structural changes). I did not add links to other directories, since the idea is one would be able to browse this contents on the Publish site instead of GitHub.

**Comment by argenos** [comment]
I just added the link on the **About** section of the repo for easy access

**Comment by tallguyjenks** [comment]
ah! so its for publish, that makes sense
