### ISSUE TITLE
Just opening a note is seen as a change in VS Code

### ISSUE THREAD

**Issue by SkepticMystic** [obsidian-community/obsidian-hub#30]
I'm not sure if others experience this, but simply opening a note in the hub vault will list that note as `modified` under VS Code's git extension. Even though no changes were made. I haven't tried pushing the changes, so I don't know what will happen. But for now I just `Discard Changes` to avoid anything unexpected.
Does anyone else have this issue?
I don't know if there is a way around it.

**Comment by kometenstaub** [comment]
Does it show any changes when you look at the diff?

**Comment by SkepticMystic** [comment]
@kometenstaub no changes, no.
In my latest PR, I tested it by committing the no-change modifications, and they just dissappeared. Nothing appeared for the unchanged note in the commit. So I guess it's a bug? But doesn't actually affect the final commit. Happy to close this out if you agree

**Comment by kometenstaub** [comment]
Yes, let's close it for now if it's just a visual thing. We can always reopen it if necessary.
