### ISSUE TITLE
Update 'Spaced Repetition Plugins' category with text from Eleanor Konik

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#309]
For the new content, please see https://discord.com/channels/686053708261228577/915679988118863933/945118307617493042

Optionally, if you can, please credit @eleanorkonik in the commit, using the mechanism described in https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Comment by lguenth** [comment]
I'll work on this today.
