### ISSUE TITLE
Enable automatic issue collection

### ISSUE THREAD

**Issue by joethei** [obsidian-community/obsidian-hub#323]
This is to enable the automatic collection of issues from plugins seeking help.
Originally created in PR #285, currently run manually.

The following things need to happen for this to be automatic:
- [x] Create a new personal GitHub API Key(at: https://github.com/settings/tokens, organizations don't seem to have that, but I can't check that). No privileges needed, the currently used, automatically created key is limited to this repository(See: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
- [ ] Test by running the `.github/scripts/update_issues.py` script manually, Should run through without issues.
- [x] Configure API Key as a secret in this repository(see: https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)
- [x] Update referenced secret in `.github/workflows/update_issues.yml` Line 29

**Comment by argenos** [comment]
I have added a token from a third account (@obsibot). However, depending on how the code works, we might hit the rate limit  anyway. From [Requests from GitHub Actions](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions), we were already exceeding 1k requests (bold mine):

> You can use the built-in GITHUB_TOKEN to authenticate requests in GitHub Actions workflows. For more information, see "[Automatic token authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)."
> 
> When using GITHUB_TOKEN, **the rate limit is 1,000 requests per hour per repository**. For requests to resources that belong to an enterprise account on GitHub.com, GitHub Enterprise Cloud's rate limit applies, and the limit is 15,000 requests per hour per repository.

The `TOKEN` I've added will only give us [5k requests total](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-user-accounts):

> User-to-server **requests are limited to 5,000 requests per hour** and per authenticated user. All requests from OAuth applications authorized by a user or a personal access token owned by the user, and requests authenticated with any of the user's authentication credentials, share the same quota of 5,000 requests per hour for that user.

I did not have a chance to test manually, but I've opened #366 with the correct secret.

**Comment by lguenth** [comment]
Awesome! Now we could try running the workflow from the patched branch and see if that works?

**Comment by argenos** [comment]
We have 522 plugins (as of now 😅 ), not sure how many requests are done for each, but that gives us roughly 10 requests per plugin (I doubt we're using that many). As the number of plugins increases, that margin will go down, so it might be something to keep in mind.

**Comment by joethei** [comment]
We would hit the rate limit at 1.666 plugins.
Each plugin makes three requests.
Once we hit that we can separate this so that every type of issue has a separate token.
