### ISSUE TITLE
broken link: "submitting your contribution"

### ISSUE THREAD

**Issue by eleanorkonik** [obsidian-community/obsidian-hub#324]
https://publish.obsidian.md/hub/CONTRIBUTING 

> Once you have added or edited the note using Obsidian, come back and check out [Submitting your contribution](https://publish.obsidian.md/hub/CONTRIBUTING#Submitting%20your%20contribution).

I think it should just go to submitting?

**Comment by kometenstaub** [comment]
The heading changed, that's why: https://publish.obsidian.md/hub/CONTRIBUTING#Submitting

It's just `Submitting` now.

**Comment by kometenstaub** [comment]
The types of contributions link doesn't work either.
