### ISSUE TITLE
Bad "Types of contributions" link

### ISSUE THREAD

**Issue by Calorion** [obsidian-community/obsidian-hub#331]
The [[#Types of contributions]] link on [CONTRIBUTING](obsidian://open?vault=obsidian-hub-0.2.1&file=CONTRIBUTING) goes nowhere.

**Comment by lguenth** [comment]
The link jumps further down the document because the Contributing notes for each type (if there are any) are outlined in the individual folder MOCs, `[[Vaults## Contributing]]`.

**Comment by Calorion** [comment]
But nothing in fact happens when I tap on that link.

**Comment by lguenth** [comment]
Yes, these links only work inside Obsidian, not on the web version. I'm making a note of that, this may be worth discussing. 
However, if you click on it inside Obsidian, it should jump down and highlight that part of the note in yellow (default theme).

![grafik](https://user-images.githubusercontent.com/69049131/157742705-2e9eec1c-eb36-4908-ab4e-fe913cdb8159.png)

**Comment by Calorion** [comment]
It does not—at least on mobile. It does nothing. Ditto with the next link—[Submitting your contribution](capacitor://localhost#Submitting%20your%20contribution)

**Comment by claremacrae** [comment]
> It does not—at least on mobile. It does nothing. Ditto with the next link—Submitting your contribution.

How are you viewing it on mobile?

Are you viewing the Hub rep directory in Obsidian on mobile?
If so, which device?

Or are you looking at the Hub website?
If so, which browser are you using?

**Comment by Calorion** [comment]
I'm using Obsidian on iPad. I downloaded the vault and opened it in Obsidian.

**Comment by kometenstaub** [comment]
I recently fixed that, you might be on an older version of the Hub. Make sure to download the zip or pull it (the releases are outdated).

**Comment by kometenstaub** [comment]
https://github.com/obsidian-community/obsidian-hub/pull/325/files
