### ISSUE TITLE
Update templates to use different sources of information

### ISSUE THREAD

**Issue by argenos** [obsidian-community/obsidian-hub#416]
Make templates recognize the source of the information, e.g. by using {{manifest.author}} in author info instead of plain placeholders: 
https://github.com/obsidian-community/obsidian-hub/blob/218d58ed3d593a36d177e44b300fb0486377bace/.github/scripts/templates/authors/author_info.md.jinja#L1

This requires making changes to the script, so we pass different dictionaries for each source: obsidian_releases (plugins.json and themes.json), manifest.json, theme.css, eventually hub.yaml, etc.

Advantages: 
- Templates become more self-documenting
- Easier to debug why some changes have happened (where did the information change)

**Comment by argenos** [comment]
Seems I had started working on this at some point: https://github.com/obsidian-community/obsidian-hub/commit/4e3c52ab4f036a486e9bf512ea31af915da6ea3e

It doesn't make sense to continue on that branch, but just to have as a reference maybe.

**Comment by claremacrae** [comment]
Argenos and I discussed this, and decided that we would put the logic in to the Python code, such as in Plugin and Theme classes - and so the templates don't need to change.
