### ISSUE TITLE
Add new content for academic writing

### ISSUE THREAD

**Issue by universvm** [obsidian-community/obsidian-hub#511]
Hi all, 

I authored these articles for academic writing that I think could be quite useful: 

- **Obsidian Tutorial for Academic Writing**: https://betterhumans.pub/obsidian-tutorial-for-academic-writing-87b038060522
- **How to Boost Your Productivity for Scientific Research Using Obsidian**: https://betterhumans.pub/how-to-boost-your-productivity-for-scientific-research-using-obsidian-fe85c98c63c8

In the discord channel I was told it could be useful to have these articles in the hub:

![Screenshot 2022-10-07 at 15 38 47](https://user-images.githubusercontent.com/17524568/194579802-23d3d43d-71d1-478b-adc0-060708977343.png)
![Screenshot 2022-10-07 at 15 41 31](https://user-images.githubusercontent.com/17524568/194580406-985f0437-8a30-4648-a1c6-1b277f7f574e.png)

as there may be a conflict of interest, please let me know if it okay to add them and if so I'll open a pr

**Comment by lguenth** [comment]
Hey @universvm, I would be delighted to see your articles added to the Hub. If you want, I think it would make sense for you to also include an author page where you could leave a few words on who you are and what you are trying to do. Thanks a lot for taking the time to ask beforehand! :orange_heart:

**Comment by lguenth** [comment]
Please also mention this issue when opening a PR, we will close this once your additions are reviewed and merged. :)

**Comment by universvm** [comment]
Thanks @lguenth ! I've opened a PR here: https://github.com/obsidian-community/obsidian-hub/pull/517 let me know if I'm missing something :)

**Comment by claremacrae** [comment]
This content has been merged and published, so I'm closing the issue.

Thank you for the contribution @universvm !
