### ISSUE TITLE
'## In The Community' in Roundup post should be at start of the line

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#535]
In the roundup file `2022-11-12: Stable Diffusion, Clean Dashboards and 2022 Workflows`, there is a line:

`💎Eleanor got Lasik on Thursday so she's trying to take it easy this weekend. This issue was guest edited by [Curtis McHale](https://curtismchale.ca).## In The Community`

The text `## In The Community` should be on a new line. I have been unable to figure out the cause of the problem.

        I will log an issue for the `## In The Community` not being at the start of a line.

_Originally posted by @claremacrae in https://github.com/obsidian-community/obsidian-hub/pull/534#discussion_r1022121167_

**Comment by claremacrae** [comment]
@AB1908 When/if you have time, please could you look at this?

**Comment by AB1908** [comment]
Okay so this looks like it's because of a callout in that specific post that is wrapped in a div. I'm guessing that this caused some parsing issues. How do we want to resolve this?

**Comment by claremacrae** [comment]
Thanks!

I did do a search in the Hub for other problem cases where there was a heading not at the start of the line - and aside from a couple where there was a space before the heading, there were not others.

So I think the choices I can think of are:

1. write clever code to handle the general case
2. write an awful hack that converts `.##` to `.\n\n##`
3. ask Eleanor if she would be willing to edit the article (or whatever appears in the RSS) to remove the callout or div - or whatever is causing the problem.

**Comment by AB1908** [comment]
I think 1 and 3 are reasonable and I'm sure Eleanor would be very open to editing it but I'm not entirely sure if those updates get pushed to the RSS. I'm also a little saddened that she can't use a callout but the less code to maintain, the better!

**Comment by claremacrae** [comment]
>  the less code to maintain, the better!

👍 

> Should we @ her in this thread or leave a message on Discord?

I don't have a preference. You decide!

**Comment by AB1908** [comment]
Hi @eleanorkonik, your call-out at the top in https://www.obsidianroundup.org/2022-11-12/ is a little tricky to work with. Would you prefer sticking to callouts or do you think changing that to something like a heading is a decent trade-off? 

You'd have to be consistent with whatever you choose and I'm also curious if Ghost actually goes back and updates the RSS. If it doesn't, that'll be another problem.

Regardless, let us know what your preferred approach is and I'll try and get an appropriate fix in. Thanks!

**Comment by claremacrae** [comment]
The published page is here:
https://publish.obsidian.md/hub/01+-+Community/Obsidian+Roundup/2022-11-12+Stable+Diffusion%2C+Clean+Dashboards+and+2022+Workflows

It currently looks like this:
![image](https://user-images.githubusercontent.com/4840096/204098826-d75b4f26-55ac-44d3-ad26-fce98d215272.png)

Discussion is also taking place on Discord, starting at:
https://discord.com/channels/686053708261228577/915679988118863933/1045836772401221662

**Comment by claremacrae** [comment]
For only one file, I am not sure it is worth writing special-case code.
However, if anyone would like to look at it, you're welcome, and here is what you would need to know.

The relevant code is at:

`.github/scripts/update_roundup.py`

- Run it from inside `.github/scripts/`, and confirm first that none of the existing files in  `01 - Community/Obsidian Roundup` changes.
- Then adjust the code and confirm that the only file that changes is the one with the problem heading.

**Comment by claremacrae** [comment]
Eleanor has kindly converted the callout to a blockquote. I re-ran update_roundup.py on my machine and this was the diff:

![image](https://user-images.githubusercontent.com/4840096/204100425-872168b5-412d-45a1-87c3-000c35446ac3.png)

So it is fixed.

I will close this when the new version is published.

**Comment by claremacrae** [comment]
Fix now published:

![image](https://user-images.githubusercontent.com/4840096/204101294-5916288f-af4e-4d35-b39e-59790d615f75.png)

Closing.
