### ISSUE TITLE
Is it possible to update Obsidian Hub?

### ISSUE THREAD

**Issue by feedhopper** [obsidian-community/obsidian-hub#539]
THANK YOU for this GREAT resource!!!

Is there a way to get the new stuff into the downloaded version of my hub? I mean: apart from downloading it each time again and unzipping ...

**Comment by claremacrae** [comment]
If you are comfortable with git, the best thing to do is to clone the repository and then you can easily update it via git.

If you are new to this, then

1. download and install [GitHub Desktop](https://desktop.github.com)
2. Click the "Open with GitHub Desktop" Link in the following:
    ![image](https://user-images.githubusercontent.com/4840096/202439318-fe00968f-bce1-4995-b594-6251d4637c41.png)
3. Using GitHub Desktop to get the latest changes every week or so.

**Comment by feedhopper** [comment]
Oh wow! THANK YOU so much, Clare.

I am very new to Github and wasn't aware of the Desktop app.

**Comment by claremacrae** [comment]
You're welcome.
I've just edited the list above to add info on how to update:
> Look for a button called something like "Fetch origin"
