### ISSUE TITLE
Make update_roundup.py use jinja2 template, so 'This note in GitHub' is added

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#547]
Currently running `update_roundup.py` removes existing `This note in GitHub` footers, which then get added back later on.

This makes the reviewing of Pull Requests by commit a little harder, as every roundup issue still in the RSS feed gets updated. 

For example, see this commit: https://github.com/obsidian-community/obsidian-hub/pull/545/commits/6797e706558f672320e42db88e0108e8d9b329ef

If `.github/scripts/update_roundup.py` could be updated so that it used a new jinja2 template, and this template included the footer template, it should all just work.

There are jinja2 helper functions (and constants) in `.github/scripts/utils.py`.

**Comment by k-schmidt** [comment]
I have a working version of this locally but I'm unsure why github isn't letting me push my branch for a PR (apologies, first time contributing to open source.)

```
(venv) kyleschmidt@kyleschmidt-mbp scripts % git push -u origin iss547                                                
remote: Permission to obsidian-community/obsidian-hub.git denied to k-schmidt.
fatal: unable to access 'https://github.com/obsidian-community/obsidian-hub.git/': The requested URL returned error: 403
```

**Comment by claremacrae** [comment]
Hi @k-schmidt Oh wow, that's great. Thank you.

I've been there and felt that pain!

### The quick way - pairing

If you would like to share your screen and for us to go through fixing it, I'm available for this next hour... my email address is in my GitHub profile.

We would go through the steps to create your fork of the project, and then push your changes to your fork.

This is something to be demoed - not safely explainable via typing

### The safe way

If you're on your own, the following is the safest thing to do at this point, and will work well if you want to contribute to other projects too.

When contributing to other repositories, the thing to do is:

1. create your own "Fork" of the project:

![image](https://user-images.githubusercontent.com/4840096/204911937-3109ba26-3d0d-4242-8299-97bdf052b5e0.png)

2. Then clone your fork to your machine. This is easiest done if you have the GitHub Desktop app...

![image](https://user-images.githubusercontent.com/4840096/204912087-0b2ccc97-f015-4233-be24-c46a2a6c8ffc.png)

3. Then go through these steps to [create a pull request.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

In particular, it is definitely worth creating a branch and then committing your changes for the fix on that branch.

It will mean recreating your work.

Good luck and thank you.

**Comment by claremacrae** [comment]
This has been done in #556 - thank you @k-schmidt!
