### ISSUE TITLE
shared Repository with reference data, similar to Wikipedia and Wikidata

### ISSUE THREAD

**Issue by SpocWeb** [obsidian-community/obsidian-hub#602]
I am interested in setting up a shared Repository, but primarily with reference data, similar to Wikipedia and Wikidata. That is less controversive and product-neutral. Therefore I would propose it as an optional GIT sub-module that can be integrated into any repo. 

Have a look at this sample repo of chemical Elements: [SpocWeb/Obsidian.Elements (github.com)](https://github.com/SpocWeb/Obsidian.Elements) 
I have integrated it as a sub-module named "_public" into a larger Repo with geographical and astronomical data (not public yet, more is to come), so everyone is warned that the sub-module is public. 

Do you think I could integrate it into your community Wiki, e.g. into a "07-Data" folder?

**Comment by kometenstaub** [comment]
We talked about this in Discord and concluded that it isn’t a good fit for this repo, because it isn’t related to Obsidian.
