### ISSUE TITLE
Broken link in one of the guides for Theme Designers (advanced)

### ISSUE THREAD

**Issue by I-Pch** [obsidian-community/obsidian-hub#603]
Hi there 😊 !

I just stumbled upon a broken external link in the article written by @chrisgrieser : [Why and How to use Stylelint for your Obsidian Theme](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Why+and+How+to+use+Stylelint+for+your+Obsidian+Theme#Why+and+How+to+use+Stylelint+for+your+Obsidian+Theme), specifically in the [Example Configuration](https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Why+and+How+to+use+Stylelint+for+your+Obsidian+Theme#Example+Configuration) section of the article 😊 .

The link under "[stylelint configuration of the theme _Shimmering Focus_](https://github.com/chrisgrieser/shimmering-focus/blob/main/.stylelintrc.json)" tries to lead us to a `.stylelintrc.json` file in the repo but it seems like the concerned file is now a `.yml` one (https://github.com/chrisgrieser/shimmering-focus/blob/main/.stylelintrc.yml)

That's it 😁 !

I wish you all an amazing day 😁

**Comment by claremacrae** [comment]
@chrisgrieser 's fix is merged and published.

**Comment by I-Pch** [comment]
Thank you @claremacrae and @chrisgrieser 🙌 !
