### ISSUE TITLE
Fix the python_tests GitHub Action

### ISSUE THREAD

**Issue by claremacrae** [obsidian-community/obsidian-hub#641]
From @argenos [on Discord earlier today](https://discord.com/channels/686053708261228577/915679988118863933/1153612378710224957):

> I have only been looking at the human ones, but it seems to me something is up with the script: https://github.com/obsidian-community/obsidian-hub/actions/runs/6061036232/job/16917693560?pr=632

@kometenstaub then did quite a lot of investigation - see later messages on discord, after the one linked above.

---

The last passing run was on 2023-05-25 - its logs have been deleted:

- https://github.com/obsidian-community/obsidian-hub/actions/runs/5082939508

The first failing run was on 2023-08-11:

- https://github.com/obsidian-community/obsidian-hub/actions/runs/5828777987

There were no other runs in between.

**Comment by kometenstaub** [comment]
Left is yours, right is a new install where the tests fail.

Major version changes for pytest, mypy, MonkeyType, certify, libcst, mypy-extensions, packaging.

<img width="745" alt="image" src="https://github.com/obsidian-community/obsidian-hub/assets/83140328/5cef0f50-bf6a-41a8-b88a-d3699a819f1f">

**Comment by kometenstaub** [comment]
I'm checking with the old `pip freeze` I had before the new `git clone`, where the tests passed.

Major version changes: pytest, MonkeyType, attrs, certify, iniconfig, libcst, mypy-extensions, packaging, urrlib3
Lower: pyparsing,

**Comment by kometenstaub** [comment]
Tests fail (your machine, my new install): pytest, mypy, MonkeyType, certify, iniconfig, charset-normalizer, libcst, mypy-extensions, packaging, urllib3.

Test pass (your machine, my old install): pytest, MonkeyType, attrs, certify, iniconfig, libcst, mypy-extensions, packaging, urrlib3

Specified in requirements.txt:

```log
jinja2
pyyaml
requests
approvaltests==3.5.0
pytest
pytest-runner
mypy
types-PyYAML
types-requests
monkeytype
github3api
markdownify
feedparser
```

Which one from this list was changed where it failed?

mypy

**Comment by kometenstaub** [comment]
`pip freeze` output from when it worked on my machine:

```
Jinja2==3.1.2
PyYAML==6.0
requests==2.30.0
approvaltests==3.5.0
pytest==7.4.2
pytest-runner==6.0.0
mypy==1.5.1
types-PyYAML==6.0.12.11
types-requests==2.31.0.2
MonkeyType==23.3.0
github3api==0.3.1
markdownify==0.11.6
feedparser==6.0.10
## The following requirements were added by pip freeze:
aiohttp==3.8.4
aiosignal==1.3.1
anyio==3.6.2
argilla==1.7.0
astroid==2.15.6
async-timeout==4.0.2
attrs==23.1.0
backoff==2.2.1
beautifulsoup4==4.12.2
bs4==0.0.1
certifi==2023.5.7
cffi==1.15.1
chardet==5.1.0
charset-normalizer==3.1.0
chromadb==0.3.23
click==8.1.3
clickhouse-connect==0.5.24
colorclass==2.2.2
commonmark==0.9.1
compressed-rtf==1.0.6
cryptography==40.0.2
dataclasses-json==0.5.7
Deprecated==1.2.13
dill==0.3.6
duckdb==0.8.0
easygui==0.98.3
ebcdic==1.1.1
empty-files==0.0.9
et-xmlfile==1.1.0
extract-msg==0.41.1
fastapi==0.95.2
filelock==3.12.0
frozenlist==1.3.3
fsspec==2023.5.0
ghostscript==0.7
h11==0.14.0
hnswlib==0.7.0
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.3
huggingface-hub==0.14.1
idna==3.4
IMAPClient==2.3.1
iniconfig==2.0.0
isort==5.12.0
jellyfish==1.0.0
joblib==1.2.0
langchain==0.0.171
lark-parser==0.12.0
lazy-object-proxy==1.9.0
libcst==1.0.1
llama-cpp-python==0.1.50
lxml==4.9.2
lz4==4.3.2
Markdown==3.4.3
MarkupSafe==2.1.2
marshmallow==3.19.0
marshmallow-enum==1.5.1
mccabe==0.7.0
monotonic==1.6
mpmath==1.3.0
msg-parser==1.2.0
msoffcrypto-tool==5.0.1
multidict==6.0.4
mypy-extensions==1.0.0
networkx==3.1
nltk==3.8.1
numexpr==2.8.4
numpy==1.23.5
obsidian-pdf-gen @ file:///Users/polaris/Private/Gitprojects/obsidian/obsidian-pdf-gen
olefile==0.46
oletools==0.60.1
openapi-schema-pydantic==1.2.4
openpyxl==3.1.2
packaging==23.1
pandas==1.5.3
pandoc==2.3
pcodedmp==1.2.6
pdf-to-scan==0.0.3
pdfminer.six==20221105
Pillow==9.5.0
platformdirs==3.9.1
pluggy==1.0.0
plumbum==1.8.1
ply==3.11
posthog==3.0.1
pycparser==2.21
pydantic==1.10.7
Pygments==2.15.1
pygpt4all==1.1.0
pygptj==2.0.3
pylint==2.17.4
pyllamacpp==2.3.0
pypandoc==1.11
pyparsing==2.4.7
pyperclip==1.8.2
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==1.0.0
python-frontmatter==1.0.0
python-magic==0.4.27
python-pptx==0.6.21
pytz==2023.3
pytz-deprecation-shim==0.1.0.post0
ranger-fm==1.9.3
red-black-tree-mod==1.20
regex==2023.5.5
rest3client==0.5.1
retrying==1.3.4
rfc3986==1.5.0
rich==13.0.1
RTFDE==0.0.2
scikit-learn==1.2.2
scipy==1.10.1
segtok==1.5.11
sentence-transformers==2.2.2
sentencepiece==0.1.99
sgmllib3k==1.0.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.4.1
SQLAlchemy==2.0.15
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tenacity==8.2.2
threadpoolctl==3.1.0
tokenizers==0.13.3
tomlkit==0.11.8
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.0
transformers==4.29.2
typer==0.9.0
types-urllib3==1.26.25.14
typing-inspect==0.8.0
typing_extensions==4.5.0
tzdata==2023.3
tzlocal==4.2
unstructured==0.6.6
urllib3==2.0.2
uvicorn==0.22.0
uvloop==0.17.0
Wand==0.6.11
watchfiles==0.19.0
websockets==11.0.3
wrapt==1.14.1
XlsxWriter==3.1.1
yake @ git+https://github.com/LIAAD/yake@374fc1c1c19eb080d5b6115cbb8d4a4324392e54
yarl==1.9.2
zstandard==0.21.0
```

`pip freeze` when it didn't after reinstall:


```log
Jinja2==3.1.2
PyYAML==6.0.1
requests==2.31.0
approvaltests==3.5.0
pytest==7.4.2
pytest-runner==6.0.0
mypy==1.5.1
types-PyYAML==6.0.12.11
types-requests==2.31.0.2
MonkeyType==23.3.0
github3api==0.3.1
markdownify==0.11.6
feedparser==6.0.10
## The following requirements were added by pip freeze:
beautifulsoup4==4.12.2
bs4==0.0.1
certifi==2023.7.22
charset-normalizer==3.2.0
empty-files==0.0.9
idna==3.4
iniconfig==2.0.0
libcst==1.0.1
MarkupSafe==2.1.3
mypy-extensions==1.0.0
packaging==23.1
pluggy==1.3.0
pyperclip==1.8.2
rest3client==0.5.1
retrying==1.3.4
sgmllib3k==1.0.0
six==1.16.0
soupsieve==2.5
types-urllib3==1.26.25.14
typing-inspect==0.9.0
typing_extensions==4.8.0
urllib3==2.0.4
```

**Comment by claremacrae** [comment]
> `pip freeze` when it didn't after reinstall:
> 
> ```
> Jinja2==3.1.2
> PyYAML==6.0.1
> requests==2.31.0
> approvaltests==3.5.0
> ...

Brilliant. With this I can reproduce the problem and so debug it - thank you!

**Comment by kometenstaub** [comment]
> `pip freeze` output from when it worked on my machine:
> 
> ```
> Jinja2==3.1.2
> PyYAML==6.0
> requests==2.30.0
> approvaltests==3.5.0
> ```

Btw, this is the global installation, I must have forgotten to activate the `venv` when I ran the tests before, but with this global config it works. (The code block after it is in the `venv`, where it doesn't work.)

**Comment by claremacrae** [comment]
I'm thinking that the best use of time is to update to a newer version of approvaltests. This is an ancient version:

```
approvaltests==3.5.0
```

- [3.5.0](https://github.com/approvals/ApprovalTests.Python/releases/tag/v3.5.0) was released Jan 30, 2022
- The latest is [9.0.0](https://github.com/approvals/ApprovalTests.Python/releases/tag/v9.0.0).

**Comment by claremacrae** [comment]
### ApprovalTests version

OK, so approvaltests 9.0.0 was the first version to actually break our tests...

So I've left it on `approvaltests==8.4.1` for now.

The changes are for now on a branch `fix-python-action`:
See the [file diffs](https://github.com/obsidian-community/obsidian-hub/compare/main...fix-python-action).

We can see that multiple GitHub Actions runs have passed...

### Options

1. Stick with specifying fixed versions for everything, as used in the most recent GitHub Actions run - as in f6894adc790c2564f22524ba074ceb50e2143fe2
    - Looks [like this](https://github.com/obsidian-community/obsidian-hub/blob/f6894adc790c2564f22524ba074ceb50e2143fe2/.github/scripts/requirements.txt)
2. Simply update the ApprovalTests version - as in 81085059068a75f882c860cdb10e9974be702939
    - Looks [like this](https://github.com/obsidian-community/obsidian-hub/blob/81085059068a75f882c860cdb10e9974be702939/.github/scripts/requirements.txt)
Currently all versions are pinned to those used by the most recent GitHub Actions run.

I'm inclined to go for 2 - I'd rather find out when we have incompatibilities.

But @kometenstaub please let me know what you think...

**Comment by claremacrae** [comment]
Forgot to say, I've also made the Python action print out the versions installed in a way that's easy to copy to a developer machine in future, for the next time we need to investigate this...

**Comment by kometenstaub** [comment]
I think we should only add the packages (all with version numbers) which were manually edited, unless those added by `pip freeze` are from your `venv` and not system-wide packages.

**Comment by claremacrae** [comment]
> I think we should only add the packages (all with version numbers) which were manually added, unless those added by `pip freeze` are from your `venv` and not system-wide packages.

Yes, the packages were obtained by:

1. setting to the latest versions of our previously list packages (well, almost-latest for approvaltests) - 7bef00137d5663ed9dbde53c61b07a546ca144a4
2. adding `python -m pip freeze -r requirements.txt` to the GitHub Actions code - and pushing the change - d290baa66deca65cd0a14043d8b2df73fc950334
3. copying the output of `python -m pip freeze -r requirements.txt` in the GitHub Actions log - f6894adc790c2564f22524ba074ceb50e2143fe2
    - See https://github.com/obsidian-community/obsidian-hub/actions/runs/6240025035/job/16939200860#step:4:190

**Comment by claremacrae** [comment]
So I think you are saying you are happy for me to create a PR from the branch... Yes?

**Comment by kometenstaub** [comment]
Yes, I am.

**Comment by claremacrae** [comment]
Sorry for not making it to this today. I've not forgotten...
