### ISSUE TITLE
community themes misses author, screenshot and modes

### ISSUE THREAD

**Issue by konhi** [obsidian-community/obsidian-hub#8]
# Actual Behavior
![image](https://user-images.githubusercontent.com/61631665/134785738-35d29628-657a-44ba-a92c-f3fa6e7a99ef.png)

# Suggested Behavior

![image](https://user-images.githubusercontent.com/61631665/134785736-3f8eb60d-78e7-4f27-8e24-528e4cac96e8.png)

_(format and order could be changed)_

`community-css-themes.json` provides additional info but it's not utilized.

**Comment by argenos** [comment]
That's true! I'll update the script!
